server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
          # CRUCIAL: Tell the deserializer to target your local class directly
        spring.json.value.default.type: "com.payflow.notification_service.event.TransactionEvent"
          # CRUCIAL: Ignore the '__TypeId__' header sent by the transaction-service
        spring.json.use.type.headers: false