name: transaction Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'transaction-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'transaction-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: transaction-service
        run: mvn clean package -DskipTests

      - name: Build Docker image
        working-directory: transaction-service
        run: docker build -t payflow-transaction-service:${{ github.sha }} .